
USE LibraryDb
GO

IF OBJECT_ID('Books') IS NOT NULL
	DROP TABLE Books

IF OBJECT_ID('Editorials') IS NOT NULL
	DROP TABLE Editorials

IF OBJECT_ID('Authors') IS NOT NULL
	DROP TABLE Authors

CREATE TABLE Authors(
Id INT PRIMARY KEY IDENTITY,
FullName VARCHAR(50) NOT NULL,
DateBirth DATE NOT NULL,
CityBirth VARCHAR(20) NOT NULL,
Email VARCHAR(30) NOT NULL
)

CREATE TABLE Editorials(
Id INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL,
[Address] VARCHAR(50) NOT NULL,
Phone VARCHAR(12) NOT NULL,
Email VARCHAR(30) NOT NULL,
MaxBook INT NOT NULL,
)

CREATE TABLE Books(
Id INT PRIMARY KEY IDENTITY,
Title VARCHAR(50) NOT NULL,
[Year] INT NOT NULL,
Genre VARCHAR(20) NOT NULL,
NumberPage INT NOT NULL,
EditorialId INT NOT NULL,
AuthorId INT NOT NULL,
FOREIGN KEY(EditorialId) REFERENCES Editorials(Id),
FOREIGN KEY(AuthorId) REFERENCES Authors(Id),
)
GO



